sonar.projectKey=vermaldonado-ia_cloud-delivery-pipeline-portafolio
sonar.organization=vermaldonado-ia

sonar.sources=app_demo/src
sonar.tests=app_demo/tests
sonar.sourceEncoding=UTF-8

sonar.python.version=3.11
sonar.exclusions=**/__pycache__/**,**/*.pyc
sonar.test.inclusions=app_demo/tests/**/*.py
sonar.python.coverage.reportPaths=app_demo/coverage.xml
